CREATE TABLE "#__gmapfp" (
  "id" serial NOT NULL,
  "nom" varchar(200) NOT NULL,
  "alias" varchar(255) NOT NULL,
  "adresse" varchar(200) NOT NULL,
  "adresse2" varchar(200) NOT NULL,
  "ville" varchar(200) NOT NULL,
  "departement" varchar(200) NOT NULL,
  "codepostal" varchar(80) NOT NULL,
  "pay" varchar(200) NOT NULL,
  "tel" varchar(30) NOT NULL,
  "tel2" varchar(30) NOT NULL,
  "fax" varchar(30) NOT NULL,
  "email" varchar(100) NOT NULL,
  "web" varchar(200) NOT NULL,
  "img" varchar(100) NOT NULL,
  "album" bigint DEFAULT 0 NOT NULL,
  "intro" text NOT NULL,
  "message" text NOT NULL,
  "horaires_prix" text NOT NULL,
  "link" varchar(200) NOT NULL,
  "article_id" bigint DEFAULT 0 NOT NULL,
  "icon" varchar(100) NOT NULL,
  "icon_label" varchar(100) NOT NULL,
  "affichage" smallint DEFAULT 0 NOT NULL,
  "marqueur" varchar(200) NOT NULL,
  "glng" varchar(20) NOT NULL,
  "glat" varchar(20) NOT NULL,
  "gzoom" varchar(2) NOT NULL,
  "catid" bigint DEFAULT 0 NOT NULL,
  "userid" bigint DEFAULT 0 NOT NULL,
  "published" bigint DEFAULT 0 NOT NULL,
  "checked_out" bigint DEFAULT 0 NOT NULL,
  "metadesc" text NOT NULL,
  "metakey" text NOT NULL,
  "ordering" bigint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id"),
);
CREATE INDEX "#__content_idx_catid" ON "#__gmapfp" ("catid");

CREATE TABLE "#__gmapfp_personnalisation" (
  "id" serial NOT NULL,
  "nom" varchar(200) NOT NULL,
  "intro_carte" text NOT NULL,
  "conclusion_carte" text NOT NULL,
  "intro_detail" text NOT NULL,
  "conclusion_detail" text NOT NULL,
  "published" bigint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id"),
);

CREATE TABLE "#__gmapfp_marqueurs" (
  "id" serial NOT NULL,
  "nom" text NOT NULL,
  "url" text NOT NULL,
  "published" bigint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id"),
);